name: CI_Actions

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository to VM
        uses: actions/checkout@v3

      - name: install libraries
        run: pip install -r requirements.txt

      - name: run programm
        run: python main.py
