name: CI_Actions

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository to VM
        uses: actions/checkout@v3

      - name: install libraries
        run: pip install -r requirements.txt

      - name: run programm
        run: python main.py
  sonarcloud:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: clone repository to VM
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install libraries
        run: pip install -r requirements.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  coveralls:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: clone repository to VM
        uses: actions/checkout@v3

      - name: install libraries
        run: |
          pip install -r requirements.txt
          pip install coverage
          pip install coverage-lcov

      - name: testing
        run: |
          coverage run --source=. -m unittest discover
          mkdir coverage
          coverage-lcov --output_file_path coverage/lcov.info

      - name: Coveralls analysis
        uses: coverallsapp/github-action@v1
